import 'dart:convert';
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

part 'app_database.g.dart';

/// A document added by the user (PDF or image).
class Documents extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get kind => text()(); // 'pdf' | 'image'
  TextColumn get filePath => text()();
  IntColumn get pageCount => integer().withDefault(const Constant(0))();
  TextColumn get subject => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// One chunk of extracted text from a document, with its embedding.
class Chunks extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id)();
  IntColumn get pageIndex => integer().withDefault(const Constant(0))();
  TextColumn get content => text()();
  BlobColumn get embedding => blob().nullable()();
}

/// A study notebook grouping documents.
class Notebooks extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// Which notebook a document belongs to.
class NotebookDocuments extends Table {
  IntColumn get notebookId => integer().references(Notebooks, #id)();
  IntColumn get documentId => integer().references(Documents, #id)();

  @override
  Set<Column> get primaryKey => {notebookId, documentId};
}

/// Flashcards auto-generated by the model.
class Flashcards extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id)();
  IntColumn get groupId =>
      integer().references(FlashcardGroups, #id).nullable()();
  TextColumn get question => text()();
  TextColumn get answer => text()();
  IntColumn get mastered => integer().withDefault(const Constant(0))();
}

/// A named flashcard group, e.g. a chapter a deck belongs to.
class FlashcardGroups extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// Planner sessions (pomodoro blocks).
class StudySessions extends Table {
  IntColumn get id => integer().autoIncrement()();
  DateTimeColumn get date => dateTime()();
  TextColumn get title => text()();
  IntColumn get minutes => integer().withDefault(const Constant(25))();
  BoolColumn get done => boolean().withDefault(const Constant(false))();
}

/// One content block in a notebook's notes pane (markdown).
class Notes extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get notebookId => integer().references(Notebooks, #id)();
  IntColumn get documentId => integer().references(Documents, #id).nullable()();
  TextColumn get content => text()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// A PDF annotation: highlight rectangle or sticky note.
class PdfAnnotations extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get documentId => integer().references(Documents, #id)();
  IntColumn get pageIndex => integer().withDefault(const Constant(0))();
  TextColumn get type => text()(); // 'highlight' | 'sticky'
  TextColumn get data => text()(); // JSON payload
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A durable memory the AI captures about the learner, reused to understand
/// intent and improve responses across Study Chat, the notebook assistant and
/// flashcard generation.
class Memories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get content => text()();
  TextColumn get category => text()(); // preference | goal | knowledge_gap | study_habit
  IntColumn get importance => integer().withDefault(const Constant(1))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A user-created playlist.
class Playlists extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A local music file inside a playlist.
class PlaylistTracks extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get playlistId => integer().references(Playlists, #id)();
  TextColumn get path => text()();
  TextColumn get title => text()();
  TextColumn get artist => text().nullable()();
  IntColumn get durationMs => integer().nullable()();
  IntColumn get order => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// Key/value settings storage.
class Settings extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}

@DriftDatabase(
  tables: [
    Documents,
    Chunks,
    Notebooks,
    NotebookDocuments,
    Flashcards,
    FlashcardGroups,
    StudySessions,
    Notes,
    PdfAnnotations,
    Memories,
    Playlists,
    PlaylistTracks,
    Settings,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');
        },
        onCreate: (m) async {
          await m.createAll();
        },
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.addColumn(documents, documents.subject);
            await m.createTable(notes);
            await m.createTable(pdfAnnotations);
            await m.createTable(playlists);
            await m.createTable(playlistTracks);
            await m.createTable(settings);
          }
          if (from < 3) {
            await m.createTable(flashcardGroups);
            await m.addColumn(flashcards, flashcards.groupId);
          }
          if (from < 4) {
            await m.createTable(memories);
          }
        },
      );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationSupportDirectory();
    final file = File(p.join(dir.path, 'moonlight.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}

/// Provide the single app-wide database instance.
final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final db = AppDatabase();
  ref.onDispose(db.close);
  return db;
});

// ---- helper encoding for embeddings ----

List<double> decodeEmbedding(Uint8List bytes) =>
    List<double>.from(jsonDecode(utf8.decode(bytes)) as List<dynamic>);

Uint8List encodeEmbedding(List<double> vector) =>
    Uint8List.fromList(utf8.encode(jsonEncode(vector)));